/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Skills from "../components/Skills";
import Blog from "../components/Blog";
import Nav from "../components/Nav";
import Header from "../components/Header";
import { useState } from "react";
import ScrollToTop from "../components/ScrollToTop";
import Brands from "../components/Brands";
import Projects from "../components/Projects";
import Experience from "../components/Experience";

export default function Home() {
    return (
        <div >
            <Head>
                <title>Chinmay Mhatre Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className=" bg-primary ">
                {/* <Nav darkMode={darkMode} setDarkMode={setDarkMode} /> */}
                <Header />
                <Experience/>
                <Projects />
                <Blog/>
                <ScrollToTop />

            </main>
        </div>
    );
}
