/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Skills from "../components/Skills";
import Blog from "../components/Blog";
import Nav from "../components/Nav";
import Header from "../components/Header";
import { useState } from "react";

export default function Home() {
    const [darkMode, setDarkMode] = useState(true);
    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Chinmay Mhatre Portfolio</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 ">
                <Nav darkMode={darkMode} setDarkMode={setDarkMode} />
                <Header />
                <Skills />
                <Blog />


            </main>
        </div>
    );
}
